### ISSUE TITLE
Unsubscribing from a feed doesn't remove starred items from that feed

### ISSUE THREAD

**Issue by maxjacobson** [feedbin/feedbin#134]
Just noticed this. Not sure if it was a deliberate choice or a consequence of some other design decision. I kind of expected them to go away, personally.

**Comment by benubois** [comment]
Hi @maxjacobson,

Yeah, this is definitely by design. I understand what you're saying and it is something I considered.

I would find deleting starred items when unsubscribing surprising. 

My thinking is that the relevance of a feed and the relevance of something I starred are separate. The source does not matter.

Is you're looking to clean up starred items of feeds you're no longer subscribed to, I think you could do this quickly with search. First [get your subscriptions list from the API](https://api.feedbin.com/v2/subscriptions.json). Then collect all the feed_ids. Your search should look like: 

```
is:starred NOT feed_id:(123 OR 321)
```

Then to unstar go down the list using the keyboard shortcut `↓` and then `s` to remove the star.

**Comment by maxjacobson** [comment]
:smile: makes sense! Thanks for the detailed reply.

Wow, feedbin's search is awesome.
