### ISSUE TITLE
AWS Endpoint

### ISSUE THREAD

**Issue by travisghansen** [feedbin/feedbin#189]
Any chance you expand the config options to support alternative s3 compatible servers like openstack or minio?

I'm trying with minio but it's not behaving the way I would have expected:
```
--- a/config/initializers/carrierwave.rb
+++ b/config/initializers/carrierwave.rb
@@ -3,9 +3,12 @@ if ENV["AWS_ACCESS_KEY_ID"] && ENV["AWS_SECRET_ACCESS_KEY"]
     config.fog_credentials = {
       provider: "AWS",
       aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
-      aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
+      aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
+      region: ENV["AWS_REGION"],
+      host: ENV["AWS_HOST"],
+      endpoint: ENV["AWS_ENDPOINT"]
     }
     config.fog_directory = ENV["AWS_S3_BUCKET"]
     config.max_file_size = 75.megabytes
   end
-end
\ No newline at end of file
+end
```

However it appears the client is attempting to upload the file?  I would have expected the file to be uploaded to the app and then in turn the app would upload to the s3 server.

Thanks!

**Comment by benubois** [comment]
Hi,

I'm not personally interested in adding this to Feedbin, but feel free to use whatever you would like for uploads.

Single-threaded Ruby application servers are [not good for handling file uploads](https://unicorn.bogomips.org/PHILOSOPHY.html#label-Slow+Clients+Are+Problematic) because it would block the process for as long as the file was uploading. To get around this limitation, Feedbin uploads [directly to S3](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html), using [CarrierWave Direct](https://github.com/dwilkie/carrierwave_direct), so anything else would have to be compatible with that or replace it.

**Comment by travisghansen** [comment]
If you take a closer look at the diff it simply adds functionality to talk with an s3 compatible endpoint other than aws.

Regarding the upload process that gives me better info to debug for sure.
