### ISSUE TITLE
Follow link and find content if RSS entry short

### ISSUE THREAD

**Issue by OJFord** [feedbin/feedbin#202]
Some feeds don't contain any 'actual' content, perhaps just an author or other metadata. For example, [Newest Python PEPs](https://www.python.org/dev/peps/peps.rss/).

I appreciate perhaps you don't want to get on the wrong side of content authors using this as a technique to drive traffic to their site (and perhaps advertising) - but often, and I think for all the cases in my feed, it just seems to be 'the way it is'. Python.org certainly isn't trying to get advertising money, for example, and I doubt they're concerned with using RSS to boost traffic to their site.

So, that's the issue, here's the actual request/suggestion:

I think it would be great if feedbin automatically followed the link when the content of a feed item is particularly short; found the real content by some heuristic (or perhaps allowing the user to pick a div ID per-feed) and rendered that instead of a giant empty pane.

I don't personally use a third-party reader at the moment, but I suppose ideally for people that do it would then proxy the actual site content into the feed as received by the reader.

**Comment by benubois** [comment]
Hi @OJFord,

Thanks for the feature request!

However, if I'm understanding you, what you suggest is easily achievable using a couple of features Feedbin already has.

1. Turn on "Sticky Full Content" under [Settings](https://feedbin.com/settings).
![screen shot 2017-02-27 at 11 08 43 am](https://cloud.githubusercontent.com/assets/133809/23375447/44ff4fc2-fcdd-11e6-842c-9da0a9b857ec.png)

2. Use the "Attempt to load full content" button to turn on this mode for the feed.
![screen shot 2017-02-27 at 11 14 03 am](https://cloud.githubusercontent.com/assets/133809/23375661/f276e99e-fcdd-11e6-8e6f-964fe746ff93.png)

Now because "Sticky Full Content" has been enabled, Feedbin will remember that you always want to attempt to load the full content for this feed.

**Comment by OJFord** [comment]
Amazing. Thank you!

I discovered feedbin after you (I assume) appeared on a podcast recently. This was one of only two things I thought was holding me back (the other's not feedbin's fault) - I'm pretty sure I'm about to be a subscriber. :slightly_smiling_face: 

Thanks for working on feedbin, and for doing it open-source! :+1:
