### ISSUE TITLE
Cannot subscribe to password protected feeds

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#306]
There is a solution in #116 to include `username:password@` in the URL, but this does not work for all feeds.

For example, I'm trying to subscribe to a feed of Confluence updates, but they've specifically disallowed this type of authentication for security reasons.

https://community.atlassian.com/t5/Confluence-questions/Authenticate-to-RSS-Feed/qaq-p/858279

It would be great if Feedbin presented actual username/password fields somewhere in the feed settings, and then used those as auth headers when requesting the feed.

**Comment by benubois** [comment]
Hi Josh,

Happy to try to help. The [HTTP library Feedbin uses](https://github.com/taf2/curb) does convert the credentials in the URL to an `Authorization` header. So adding a username and password prompt would not change the HTTP request that gets made to the host.

There are two things you could try:

1. The [user information portion should be percent-encoded](https://tools.ietf.org/html/rfc3986#section-3.2.1) so your login info would become: `user%40host.com:password`. Your password may need to be percent encoded too if it contains significant characters.

2. The [Atlassian Feed Builder page](https://confluence.atlassian.com/confcloud/the-rss-feed-builder-724765362.html?_ga=2.165641148.2070466146.1551645950-1872606957.1551645950), says you should add the parameter `os_authType=basic` to the url. This would make the full url something like:

```
http://user%40host.com:password@company.atlassian.com/feed?os_authType=basic
```

Please let me know how that goes.

Thanks!

**Comment by endquote** [comment]
I think the percent-encoding did the trick. 👍

**Comment by abomi** [comment]
Yes, the %40 in place of the "@" in the email address fixed the problem for me.

At a minimum, you should update the support article on this topic:  https://feedbin.com/help/password-protected-feeds/

The bug is probably that the username includes the @ and the @ is separating the password from the feed's domain.  It likely exists where the password contains any of the parsing/delimiter characters as well.  Best solution would be supporting this feature in the GUI rather than trying to parse a complex string of characters which could contain anything.  The existing text box does not support 100+ character passwords, anyway.
