### ISSUE TITLE
Feed is not updated

### ISSUE THREAD

**Issue by miso-belica** [feedbin/feedbin#331]
Hi, I am subscribed to this feed https://py.b.cz/helpers/facebook/doc-diff.xml but I can's see any new updates even if there are new entries. For example, an entry published at 2019-06-11T05:00:13Z is not shown for me and on the subscription page I can see that the feed was updated 2 months ago, what is not true. Can you check it please and fix the problem? I tried it in another RSS reader and it works fine there.

**Comment by dentarg** [comment]
Could `<link href="http://127.0.0.1:5000/helpers/facebook/doc-diff.xml" rel="self" />` in the feed be the issue? https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpy.b.cz%2Fhelpers%2Ffacebook%2Fdoc-diff.xml

**Comment by miso-belica** [comment]
@dentarg Thanks for the idea, but I updated the feed and it does not seem to help :(

**Comment by benubois** [comment]
Hi @miso-belica,

I believe this feed is reusing `<id>` tags. Feedbin uses the `id` to uniquely identify entries, so any entry that shares the same `id` looks like a duplicate.

For example this entry is not in Feedbin:

title: https://developers.facebook.com/docs/graph-api/advanced/rate-limiting
id: https://developers.facebook.com/docs/graph-api/advanced/rate-limiting
date: 2019-06-11T05:00:13Z

Because it shares the same `id` as this one from over a month earlier:

title: https://developers.facebook.com/docs/graph-api/advanced/rate-limiting
id: https://developers.facebook.com/docs/graph-api/advanced/rate-limiting
date: 2019-05-01T02:00:16Z

This would need to be fixed by the publisher.

Thanks!

Ben

**Comment by miso-belica** [comment]
@benubois Ou, thanks for the that. I am going to fix it :)
