### ISSUE TITLE
Newsletters being blocked as spam

### ISSUE THREAD

**Issue by endquote** [feedbin/feedbin#525]
I frequently forward email to feedbin to make use of the newsletters feature. Lately some of it has getting bounced as spam, even though they are regular newsletters from substack etc. 

Since the email address is unique to me and never shared, maybe spam filtering could be disabled, or at least be set to a higher threshold. 

![image](https://user-images.githubusercontent.com/330010/92307589-5a508200-ef4c-11ea-8100-5e51fbd85923.jpeg)

**Comment by benubois** [comment]
Unfortunately it looks like the false positive rate for Mailgun's spam filter is too high. I'll look into another solution.

> Since the email address is unique to me and never shared, maybe spam filtering could be disabled.

In a perfect world yes, but spam always finds a way. Currently, seemingly legit newsletter providers are selling or otherwise leaking their subscriber lists so Feedbin sees quite a bit of the stuff.
