### ISSUE TITLE
Most Recent Article in Feed Delayed

### ISSUE THREAD

**Issue by Anthony-Margotta** [feedbin/feedbin#649]
I'm seeing substantial (+12hrs) delays in the appearance of new articles from https://www.platformer.news/feed

I've confirmed that the article appears when expected via the built-in feed aggregator of the Reeder app on iOS.

(I'm a subscriber, not an owner of this feed; I just want to be able to receive timely updates)

Link to gist: https://gist.github.com/Anthony-Margotta/3dcc32fed267dde82801a6fb75f245b3

**Comment by benubois** [comment]
Hi @Anthony-Margotta 

Sorry for the trouble!

Looks like they're throttling Feedbin. This is common on platforms that have many feeds (Substack in this case) because their rate limiting is aggregated across the platform. They're also not accounting for automated traffic for things that are exclusively accessed by bots (like RSS feeds).

This would need to be fixed by the publisher. You could also sign up for the newsletter using your Feedbin newsletter address.

**Comment by Anthony-Margotta** [comment]
Thanks for explaining! I was using the newsletter address but I’m happier with the formatting from the RSS feed.
